language: node_js
node_js:
    - "8"
env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
before_install:
  # Check that default ruby changes after `rvm install` step
  - ruby --version
  - rvm install 2.5.7
  - ruby --version
install:
    - npm install -g vuepress
    - npm install
script:
    - npm run build
cache:
    directories:
        - "node_modules"
notifications:
    email: false
